name: tefa_ids
description: "A new Flutter project."
version: 1.0.0

environment:
  sdk: ">=3.5.1 <3.6.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
